export const elements = {
    mainNav: document.querySelector('#mainNav'),
    backBtn: document.querySelector("#backBtn"),
    headerBtn: document.querySelector('#headerBtn'),
    searchForm: document.querySelector('#search-form'),
    query: document.querySelector('#query'),
    profilsCards: document.querySelector('#profilsCards'),
    cardBox: document.querySelector('#card'),
    repos: document.querySelector('#repos'),
    repoNav: document.querySelector('#repoNav'),
    likesTile: document.querySelector('#likesTile'),
    likeCards: document.querySelector('#likeCards'),
    likesNavButton: document.querySelector('#likesNavButton'),
    closeLikesBtn: document.querySelector('#closeLikesBtn'),
    likeList: document.querySelector('#likeList'),
    moreBtn: document.querySelector('#moreBtn'),
};